# CALIDAD DE DATOS

## IMPORTAR PAQUETES

In [4]:
import warnings

warnings.filterwarnings("ignore", category=DeprecationWarning)

C:\Users\Lenovo\anaconda3\envs\leadkaggle\Lib\site-packages\jupyter_client\session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
C:\Users\Lenovo\anaconda3\envs\leadkaggle\Lib\site-packages\jupyter_client\session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
C:\Users\Lenovo\anaconda3\envs\leadkaggle\Lib\site-packages\jupyter_client\session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [5]:
import numpy as np
import pandas as pd
from janitor import clean_names

#Automcompletar rápido
%config IPCompleter.greedy=True

## IMPORTAR LOS DATOS

Sustituir la ruta del proyecto.

In [6]:
ruta_proyecto = 'C:/Users/Lenovo/Documents/portafolio_ds/automation/LEAD_KAGGLE'

In [7]:
nombre_archivo_datos = 'trabajo.csv'

Cargar los datos.

In [8]:
ruta_completa = ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_archivo_datos

df = pd.read_csv(ruta_completa,index_col=0)
df

,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
Prospect ID,,,,,,,,,,,,,,,,,,,,,
7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.00,Page Visited on Website,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.50,Email Opened,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,Email Opened,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,Unreachable,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,Converted to Lead,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,Email Marked Spam,...,No,Potential Lead,Mumbai,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,SMS Sent,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,SMS Sent,...,No,Potential Lead,Mumbai,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,SMS Sent,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,SMS Sent,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

## CORRECCIÓN DE NOMBRES DE VARIABLES

### Corrección automática

In [9]:
df = clean_names(df)
df

,lead_number,lead_origin,lead_source,do_not_email,do_not_call,converted,totalvisits,total_time_spent_on_website,page_views_per_visit,last_activity,...,get_updates_on_dm_content,lead_profile,city,asymmetrique_activity_index,asymmetrique_profile_index,asymmetrique_activity_score,asymmetrique_profile_score,i_agree_to_pay_the_amount_through_cheque,a_free_copy_of_mastering_the_interview,last_notable_activity
Prospect ID,,,,,,,,,,,,,,,,,,,,,
7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.00,Page Visited on Website,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.50,Email Opened,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,Email Opened,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,Unreachable,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,Converted to Lead,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,Email Marked Spam,...,No,Potential Lead,Mumbai,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,SMS Sent,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,SMS Sent,...,No,Potential Lead,Mumbai,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,SMS Sent,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,SMS Sent,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [10]:
#Revisar si se necesita corregir manualmente los nombres
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6468 entries, 7927b2df-8bba-4d29-b9a2-b6e0beafe620 to 571b5c8e-a5b2-4d57-8574-f2ffb06fdeff
Data columns (total 36 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   lead_number                                    6468 non-null   int64
 1   lead_origin                                    6468 non-null   object
 2   lead_source                                    6445 non-null   object
 3   do_not_email                                   6468 non-null   object
 4   do_not_call                                    6468 non-null   object
 5   converted                                      6468 non-null   int64
 6   totalvisits                                    6369 non-null   float64
 7   total_time_spent_on_website                    6468 non-null   int64
 8   page_views_per_visit                           6369 non-null   float64
 9   last_activity                                  6392 non-null   object
 10  country                                        4732 non-null   object
 11  specialization                                 5438 non-null   object
 12  how_did_you_hear_about_x_education             4908 non-null   object
 13  what_is_your_current_occupation                4563 non-null   object
 14  what_matters_most_to_you_in_choosing_a_course  4550 non-null   object
 15  search                                         6468 non-null   object
 16  magazine                                       6468 non-null   object
 17  newspaper_article                              6468 non-null   object
 18  x_education_forums                             6468 non-null   object
 19  newspaper                                      6468 non-null   object
 20  digital_advertisement                          6468 non-null   object
 21  through_recommendations                        6468 non-null   object
 22  receive_more_updates_about_our_courses         6468 non-null   object
 23  tags                                           4114 non-null   object
 24  lead_quality                                   3124 non-null   object
 25  update_me_on_supply_chain_content              6468 non-null   object
 26  get_updates_on_dm_content                      6468 non-null   object
 27  lead_profile                                   4550 non-null   object
 28  city                                           5451 non-null   object
 29  asymmetrique_activity_index                    3532 non-null   object
 30  asymmetrique_profile_index                     3532 non-null   object
 31  asymmetrique_activity_score                    3532 non-null   float64
 32  asymmetrique_profile_score                     3532 non-null   float64
 33  i_agree_to_pay_the_amount_through_cheque       6468 non-null   object
 34  a_free_copy_of_mastering_the_interview         6468 non-null   object
 35  last_notable_activity                          6468 non-null   object
dtypes: float64(4), int64(3), object(29)
memory usage: 1.8+ MB

### Corrección manual

In [11]:
df.rename(columns = {'totalvisits':'total_visits'}, inplace=True)
df

,lead_number,lead_origin,lead_source,do_not_email,do_not_call,converted,total_visits,total_time_spent_on_website,page_views_per_visit,last_activity,...,get_updates_on_dm_content,lead_profile,city,asymmetrique_activity_index,asymmetrique_profile_index,asymmetrique_activity_score,asymmetrique_profile_score,i_agree_to_pay_the_amount_through_cheque,a_free_copy_of_mastering_the_interview,last_notable_activity
Prospect ID,,,,,,,,,,,,,,,,,,,,,
7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.00,Page Visited on Website,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.50,Email Opened,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,Email Opened,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,Unreachable,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,Converted to Lead,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,Email Marked Spam,...,No,Potential Lead,Mumbai,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,SMS Sent,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,SMS Sent,...,No,Potential Lead,Mumbai,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,SMS Sent,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,SMS Sent,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

## VISIÓN GENERAL

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6468 entries, 7927b2df-8bba-4d29-b9a2-b6e0beafe620 to 571b5c8e-a5b2-4d57-8574-f2ffb06fdeff
Data columns (total 36 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   lead_number                                    6468 non-null   int64
 1   lead_origin                                    6468 non-null   object
 2   lead_source                                    6445 non-null   object
 3   do_not_email                                   6468 non-null   object
 4   do_not_call                                    6468 non-null   object
 5   converted                                      6468 non-null   int64
 6   total_visits                                   6369 non-null   float64
 7   total_time_spent_on_website                    6468 non-null   int64
 8   page_views_per_visit                           6369 non-null   float64
 9   last_activity                                  6392 non-null   object
 10  country                                        4732 non-null   object
 11  specialization                                 5438 non-null   object
 12  how_did_you_hear_about_x_education             4908 non-null   object
 13  what_is_your_current_occupation                4563 non-null   object
 14  what_matters_most_to_you_in_choosing_a_course  4550 non-null   object
 15  search                                         6468 non-null   object
 16  magazine                                       6468 non-null   object
 17  newspaper_article                              6468 non-null   object
 18  x_education_forums                             6468 non-null   object
 19  newspaper                                      6468 non-null   object
 20  digital_advertisement                          6468 non-null   object
 21  through_recommendations                        6468 non-null   object
 22  receive_more_updates_about_our_courses         6468 non-null   object
 23  tags                                           4114 non-null   object
 24  lead_quality                                   3124 non-null   object
 25  update_me_on_supply_chain_content              6468 non-null   object
 26  get_updates_on_dm_content                      6468 non-null   object
 27  lead_profile                                   4550 non-null   object
 28  city                                           5451 non-null   object
 29  asymmetrique_activity_index                    3532 non-null   object
 30  asymmetrique_profile_index                     3532 non-null   object
 31  asymmetrique_activity_score                    3532 non-null   float64
 32  asymmetrique_profile_score                     3532 non-null   float64
 33  i_agree_to_pay_the_amount_through_cheque       6468 non-null   object
 34  a_free_copy_of_mastering_the_interview         6468 non-null   object
 35  last_notable_activity                          6468 non-null   object
dtypes: float64(4), int64(3), object(29)
memory usage: 1.8+ MB

## TIPOS DE DATOS

### Identificación

In [13]:
df.dtypes

lead_number                                        int64
lead_origin                                       object
lead_source                                       object
do_not_email                                      object
do_not_call                                       object
converted                                          int64
total_visits                                     float64
total_time_spent_on_website                        int64
page_views_per_visit                             float64
last_activity                                     object
country                                           object
specialization                                    object
how_did_you_hear_about_x_education                object
what_is_your_current_occupation                   object
what_matters_most_to_you_in_choosing_a_course     object
search                                            object
magazine                                          object
newspaper_article                                 object
x_education_forums                                object
newspaper                                         object
digital_advertisement                             object
through_recommendations                           object
receive_more_updates_about_our_courses            object
tags                                              object
lead_quality                                      object
update_me_on_supply_chain_content                 object
get_updates_on_dm_content                         object
lead_profile                                      object
city                                              object
asymmetrique_activity_index                       object
asymmetrique_profile_index                        object
asymmetrique_activity_score                      float64
asymmetrique_profile_score                       float64
i_agree_to_pay_the_amount_through_cheque          object
a_free_copy_of_mastering_the_interview            object
last_notable_activity                             object
dtype: object

### Corrección

In [14]:
df = df.astype({'total_visits':'Int64'})

df.dtypes

lead_number                                        int64
lead_origin                                       object
lead_source                                       object
do_not_email                                      object
do_not_call                                       object
converted                                          int64
total_visits                                       Int64
total_time_spent_on_website                        int64
page_views_per_visit                             float64
last_activity                                     object
country                                           object
specialization                                    object
how_did_you_hear_about_x_education                object
what_is_your_current_occupation                   object
what_matters_most_to_you_in_choosing_a_course     object
search                                            object
magazine                                          object
newspaper_article                                 object
x_education_forums                                object
newspaper                                         object
digital_advertisement                             object
through_recommendations                           object
receive_more_updates_about_our_courses            object
tags                                              object
lead_quality                                      object
update_me_on_supply_chain_content                 object
get_updates_on_dm_content                         object
lead_profile                                      object
city                                              object
asymmetrique_activity_index                       object
asymmetrique_profile_index                        object
asymmetrique_activity_score                      float64
asymmetrique_profile_score                       float64
i_agree_to_pay_the_amount_through_cheque          object
a_free_copy_of_mastering_the_interview            object
last_notable_activity                             object
dtype: object

## VALORES ÚNICOS

### Identificación

In [15]:
df

,lead_number,lead_origin,lead_source,do_not_email,do_not_call,converted,total_visits,total_time_spent_on_website,page_views_per_visit,last_activity,...,get_updates_on_dm_content,lead_profile,city,asymmetrique_activity_index,asymmetrique_profile_index,asymmetrique_activity_score,asymmetrique_profile_score,i_agree_to_pay_the_amount_through_cheque,a_free_copy_of_mastering_the_interview,last_notable_activity
Prospect ID,,,,,,,,,,,,,,,,,,,,,
7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0,0,0.00,Page Visited on Website,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5,674,2.50,Email Opened,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2,1532,2.00,Email Opened,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1,305,1.00,Unreachable,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2,1428,1.00,Converted to Lead,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8,1845,2.67,Email Marked Spam,...,No,Potential Lead,Mumbai,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2,238,2.00,SMS Sent,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2,199,2.00,SMS Sent,...,No,Potential Lead,Mumbai,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3,499,3.00,SMS Sent,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6,1279,3.00,SMS Sent,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [16]:
df.nunique().sort_values()

update_me_on_supply_chain_content                   1
get_updates_on_dm_content                           1
i_agree_to_pay_the_amount_through_cheque            1
receive_more_updates_about_our_courses              1
newspaper                                           1
x_education_forums                                  1
magazine                                            1
through_recommendations                             2
digital_advertisement                               2
a_free_copy_of_mastering_the_interview              2
search                                              2
newspaper_article                                   2
converted                                           2
do_not_call                                         2
do_not_email                                        2
what_matters_most_to_you_in_choosing_a_course       3
asymmetrique_activity_index                         3
asymmetrique_profile_index                          3
lead_origin                                         4
lead_quality                                        5
what_is_your_current_occupation                     6
lead_profile                                        6
city                                                7
asymmetrique_profile_score                         10
how_did_you_hear_about_x_education                 10
asymmetrique_activity_score                        12
last_notable_activity                              16
last_activity                                      16
specialization                                     19
lead_source                                        19
tags                                               25
total_visits                                       33
country                                            37
page_views_per_visit                               94
total_time_spent_on_website                      1557
lead_number                                      6468
dtype: int64

### Corrección

In [17]:
df.drop(columns = {'update_me_on_supply_chain_content','get_updates_on_dm_content','i_agree_to_pay_the_amount_through_cheque','receive_more_updates_about_our_courses','newspaper','x_education_forums','magazine'}, inplace = True)

In [18]:
df.nunique().sort_values()

through_recommendations                             2
newspaper_article                                   2
search                                              2
do_not_email                                        2
do_not_call                                         2
converted                                           2
a_free_copy_of_mastering_the_interview              2
digital_advertisement                               2
what_matters_most_to_you_in_choosing_a_course       3
asymmetrique_profile_index                          3
asymmetrique_activity_index                         3
lead_origin                                         4
lead_quality                                        5
lead_profile                                        6
what_is_your_current_occupation                     6
city                                                7
how_did_you_hear_about_x_education                 10
asymmetrique_profile_score                         10
asymmetrique_activity_score                        12
last_notable_activity                              16
last_activity                                      16
specialization                                     19
lead_source                                        19
tags                                               25
total_visits                                       33
country                                            37
page_views_per_visit                               94
total_time_spent_on_website                      1557
lead_number                                      6468
dtype: int64

## DUPLICADOS

### Identificación

In [19]:
df.duplicated().sum()

0

### Corrección

In [20]:
#df.drop_duplicates(inplace = True)

## SEPARAR NUMÉRICAS Y CATEGÓRICAS

### Categóricas

In [21]:
cat = df.select_dtypes(exclude = 'number').copy()

### Numéricas

In [22]:
num = df.select_dtypes(include = 'number').copy()

## GESTIÓN DE CATEGÓRICAS

### Nulos

#### Identificación

In [23]:
cat.isna().sum().sort_values(ascending = False)

lead_quality                                     3344
asymmetrique_profile_index                       2936
asymmetrique_activity_index                      2936
tags                                             2354
what_matters_most_to_you_in_choosing_a_course    1918
lead_profile                                     1918
what_is_your_current_occupation                  1905
country                                          1736
how_did_you_hear_about_x_education               1560
specialization                                   1030
city                                             1017
last_activity                                      76
lead_source                                        23
lead_origin                                         0
a_free_copy_of_mastering_the_interview              0
newspaper_article                                   0
through_recommendations                             0
digital_advertisement                               0
search                                              0
do_not_call                                         0
do_not_email                                        0
last_notable_activity                               0
dtype: int64

#### Corrección

##### Eliminar la variable

In [24]:
cat.drop(columns = 'lead_quality',inplace = True)

##### Imputar por un valor

###### Variables a imputar

También se 'imputan' las variables que no tienen nulos como una medida de precaución para datos futuros

In [25]:
var_imputar_valor = ['tags',
                     'asymmetrique_profile_index',
                     'lead_origin',                                         
                     'a_free_copy_of_mastering_the_interview',              
                     'newspaper_article',                                   
                     'through_recommendations',                             
                     'digital_advertisement',                             
                     'search',                                              
                     'do_not_call',                                         
                     'do_not_email',                                       
                     'last_notable_activity']

###### Valor por el que imputar

In [26]:
valor = 'Unknown'

###### Imputar

In [27]:
cat[var_imputar_valor] = cat[var_imputar_valor].fillna(valor)

###### Otra imputación por valor

In [27]:
var_imputar_valor = ['city']
valor = 'Select'
cat[var_imputar_valor] = cat[var_imputar_valor].fillna(valor)

##### Imputar por la moda

###### Variables a imputar

In [28]:
var_imputar_moda = ['asymmetrique_activity_index',
    'what_matters_most_to_you_in_choosing_a_course',
    'lead_profile',
    'what_is_your_current_occupation',
    'country',
    'specialization',
    'last_activity',
    'lead_source',
    'how_did_you_hear_about_x_education']

###### Funcion para imputar con la moda

In [29]:
def imputar_moda(variable):
    return(variable.fillna(variable.mode()[0]))

###### Imputar con la moda

In [30]:
cat[var_imputar_moda] = cat[var_imputar_moda].apply(imputar_moda)

In [31]:
cat.isna().sum().sort_values(ascending = False)

lead_origin                                      0
newspaper_article                                0
a_free_copy_of_mastering_the_interview           0
asymmetrique_profile_index                       0
asymmetrique_activity_index                      0
city                                             0
lead_profile                                     0
tags                                             0
through_recommendations                          0
digital_advertisement                            0
search                                           0
lead_source                                      0
what_matters_most_to_you_in_choosing_a_course    0
what_is_your_current_occupation                  0
how_did_you_hear_about_x_education               0
specialization                                   0
country                                          0
last_activity                                    0
do_not_call                                      0
do_not_email                                     0
last_notable_activity                            0
dtype: int64

### Atípicos

#### Categorías poco frecuentes

##### Función para agrupar categorías raras en 'OTROS'

In [32]:
def agrupar_cat_raras(variable, criterio):
    #Calcula las frecuencias
    frecuencias = variable.value_counts(normalize=True)
    #Identifica las que están por debajo del criterio
    temp = [cada for cada in frecuencias.loc[frecuencias < criterio].index.values]
    #Las recodifica en 'OTHER'
    temp2 = np.where(variable.isin(temp),'OTHER',variable)
    #Devuelve el resultado
    return(temp2)

##### Variables a imputar

In [33]:
var_agrupar_cat_raras = ['lead_origin',
                        'lead_source',
                        'last_activity',
                        'country',
                        'specialization',
                        'how_did_you_hear_about_x_education',
                        'what_is_your_current_occupation',
                        'what_matters_most_to_you_in_choosing_a_course',
                        'tags',
                        'lead_profile',
                        'city',
                        'last_notable_activity']

##### Aplicar

In [34]:
for variable in var_agrupar_cat_raras:
    cat[variable] = agrupar_cat_raras(cat[variable],criterio = 0.02)

In [35]:
# Iterar sobre todas las columnas del DataFrame y aplicar value_counts() solo a las variables categóricas
for col in cat.select_dtypes(include=['object', 'category']).columns:
    print(f"Value counts for {col}:")
    print(cat[col].value_counts())
    print("\n")

Value counts for lead_origin:
lead_origin
Landing Page Submission    3401
API                        2532
Lead Add Form               494
OTHER                        41
Name: count, dtype: int64


Value counts for lead_source:
lead_source
Google            2018
Direct Traffic    1782
Olark Chat        1256
Organic Search     796
Reference          370
OTHER              246
Name: count, dtype: int64


Value counts for do_not_email:
do_not_email
No     5952
Yes     516
Name: count, dtype: int64


Value counts for do_not_call:
do_not_call
No     6466
Yes       2
Name: count, dtype: int64


Value counts for last_activity:
last_activity
Email Opened               2477
SMS Sent                   1885
Olark Chat Conversation     699
Page Visited on Website     447
Converted to Lead           313
Email Bounced               236
OTHER                       212
Email Link Clicked          199
Name: count, dtype: int64


Value counts for country:
country
India    6269
OTHER     199
Name: count, dtype: int64


Value counts for specialization:
specialization
Select                               2389
Finance Management                    673
Marketing Management                  587
OTHER                                 583
Human Resource Management             578
Operations Management                 352
Business Administration               284
IT Projects Management                252
Banking, Investment And Insurance     241
Supply Chain Management               239
Travel and Tourism                    151
Media and Advertising                 139
Name: count, dtype: int64


Value counts for how_did_you_hear_about_x_education:
how_did_you_hear_about_x_education
Select                   5089
Online Search             562
OTHER                     370
Word Of Mouth             227
Student of SomeSchool     220
Name: count, dtype: int64


Value counts for what_is_your_current_occupation:
what_is_your_current_occupation
Unemployed              5814
Working Professional     478
Student                  154
OTHER                     22
Name: count, dtype: int64


Value counts for what_matters_most_to_you_in_choosing_a_course:
what_matters_most_to_you_in_choosing_a_course
Better Career Prospects    6465
OTHER                         3
Name: count, dtype: int64


Value counts for search:
search
No     6460
Yes       8
Name: count, dtype: int64


Value counts for newspaper_article:
newspaper_article
No     6467
Yes       1
Name: count, dtype: int64


Value counts for digital_advertisement:
digital_advertisement
No     6465
Yes       3
Name: count, dtype: int64


Value counts for through_recommendations:
through_recommendations
No     6464
Yes       4
Name: count, dtype: int64


Value counts for tags:
tags
Unknown                                2354
Will revert after reading the email    1458
Ringing                                 823
OTHER                                   599
Interested in other courses             358
Already a student                       325
Closed by Horizzon                      257
switched off                            164
Busy                                    130
Name: count, dtype: int64


Value counts for lead_profile:
lead_profile
Select                   4801
Potential Lead           1134
Other Leads               330
Student of SomeSchool     175
OTHER                      28
Name: count, dtype: int64


Value counts for city:
city
Select                         2583
Mumbai                         2219
Thane & Outskirts               519
Other Cities                    490
Other Cities of Maharashtra     323
Other Metro Cities              285
OTHER                            49
Name: count, dtype: int64


Value counts for asymmetrique_activity_index:
asymmetrique_activity_index
02.Medium    5618
01.High       583
03.Low        267
Name: count, dtype: int64


Value counts for asymmetrique_profile_index:
asymmetrique_profile_index
Unknown      2936
02.Medium    1976
01.High      1531
03.Low         25
Name: count, dtype: int64


Value counts for a_free_copy_of_mastering_the_interview:
a_free_copy_of_mastering_the_interview
No     4427
Yes    2041
Name: count, dtype: int64


Value counts for last_notable_activity:
last_notable_activity
Modified                   2427
Email Opened               1963
SMS Sent                   1486
OTHER                       241
Page Visited on Website     218
Email Link Clicked          133
Name: count, dtype: int64

## GESTIÓN DE NUMÉRICAS

In [36]:
cat.tags.value_counts()

tags
Unknown                                2354
Will revert after reading the email    1458
Ringing                                 823
OTHER                                   599
Interested in other courses             358
Already a student                       325
Closed by Horizzon                      257
switched off                            164
Busy                                    130
Name: count, dtype: int64

### Nulos

#### Identificación

In [37]:
num.isna().sum().sort_values(ascending = False)

asymmetrique_activity_score    2936
asymmetrique_profile_score     2936
total_visits                     99
page_views_per_visit             99
lead_number                       0
converted                         0
total_time_spent_on_website       0
dtype: int64

In [38]:
num.asymmetrique_activity_score.value_counts().sort_values(ascending=False)

asymmetrique_activity_score
14.0    1220
15.0     905
13.0     557
16.0     322
17.0     259
12.0     147
11.0      71
10.0      41
9.0        5
18.0       2
8.0        2
7.0        1
Name: count, dtype: int64

In [39]:
num.asymmetrique_profile_score.value_counts().sort_values(ascending=False)

asymmetrique_profile_score
15.0    1246
18.0     746
16.0     426
17.0     404
20.0     211
19.0     170
14.0     167
13.0     137
12.0      18
11.0       7
Name: count, dtype: int64

Nota sobre las variables 'asymmetrique...'
* la variable categórica es un índice
* La variable numérica es un score/puntuación

In [40]:
num.describe().T

,count,mean,std,min,25%,50%,75%,max
lead_number,6468.0,617407.262987,23420.090083,579533.0,596561.25,616013.5,637710.5,660737.0
converted,6468.0,0.382189,0.48596,0.0,0.0,0.0,1.0,1.0
total_visits,6369.0,3.344167,3.924811,0.0,1.0,3.0,5.0,141.0
total_time_spent_on_website,6468.0,481.514224,544.603621,0.0,9.0,243.0,928.25,2272.0
page_views_per_visit,6369.0,2.340036,2.083269,0.0,1.0,2.0,3.0,24.0
asymmetrique_activity_score,3532.0,14.30068,1.400194,7.0,14.0,14.0,15.0,18.0
asymmetrique_profile_score,3532.0,16.326161,1.806896,11.0,15.0,16.0,18.0,20.0

#### Corrección

##### Imputar por la mediana

###### Variables a imputar

In [41]:
var_imputar_mediana = num.columns.to_list()

###### Funcion para imputar con la mediana

In [42]:
def imputar_mediana(variable):
    if pd.api.types.is_integer_dtype(variable):
        return(variable.fillna(int(variable.median())))
    else:
        return(variable.fillna(variable.median()))

###### Imputar con la mediana

In [43]:
num[var_imputar_mediana] = num[var_imputar_mediana].apply(imputar_mediana)

In [44]:
num.isna().sum().sort_values(ascending = False)

lead_number                    0
converted                      0
total_visits                   0
total_time_spent_on_website    0
page_views_per_visit           0
asymmetrique_activity_score    0
asymmetrique_profile_score     0
dtype: int64

### Atípicos

##### Identificación

###### Definir el número de desviaciones típicas

In [45]:
num_desv_tip = 4

###### Función que devuelve los índices de los atípicos

In [46]:
def atipicos_desv_tip(variable, num_desv_tip = 4):
    #sacamos los nulos por ahora
    variable = variable.dropna()
    #calculamos los límites
    media = np.mean(variable)
    sd = np.std(variable)
    umbral = sd * num_desv_tip
    lim_inf = media - umbral
    lim_sup = media + umbral
    #encontramos los índices de los que están fuera de los límites
    indices = [indice for indice,valor in variable.items() if valor < lim_inf or valor > lim_sup]
    return(indices)

###### Función que cuenta el número de atípicos

In [47]:
def conteo_atipicos(df,variable, num_desv_tip = 4):
    atipicos = atipicos_desv_tip(df[variable], num_desv_tip)
    return(df.loc[atipicos,variable].value_counts())

###### Variables a aplicar

In [48]:
var_atipicos_dt = num.columns.to_list()

###### Aplicar

In [49]:
for variable in var_atipicos_dt:
    print('\n' + variable + ':\n')
    print(conteo_atipicos(num,variable,num_desv_tip))

lead_number:

Series([], Name: count, dtype: int64)

converted:

Series([], Name: count, dtype: int64)

total_visits:

total_visits
19     7
21     5
20     5
24     5
25     4
23     4
29     2
27     2
22     1
30     1
141    1
28     1
74     1
54     1
Name: count, dtype: Int64

total_time_spent_on_website:

Series([], Name: count, dtype: int64)

page_views_per_visit:

page_views_per_visit
11.00    11
14.00     6
15.00     4
13.00     3
16.00     3
12.00     1
12.33     1
24.00     1
14.50     1
Name: count, dtype: int64

asymmetrique_activity_score:

asymmetrique_activity_score
9.0    5
8.0    2
7.0    1
Name: count, dtype: int64

asymmetrique_profile_score:

Series([], Name: count, dtype: int64)

##### Corrección

#### Por winsorización manual para una variable

##### Corrección

###### Aplicar

In [50]:
num['page_views_per_visit'] = num['page_views_per_visit'].clip(0, 20)
num['total_visits'] = num['total_visits'].clip(0, 50)

## GUARDAR DATASETS TRAS CALIDAD DE DATOS

### Definir los nombres de los archivos

In [51]:
ruta_trabajo = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'trabajo_resultado_calidad.pickle'
ruta_cat = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'cat_resultado_calidad.pickle'
ruta_num = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'num_resultado_calidad.pickle'

### Guardar los archivos

In [52]:
df.to_pickle(ruta_trabajo)
cat.to_pickle(ruta_cat)
num.to_pickle(ruta_num)