# TRANSFORMACIÓN DE DATOS

## IMPORTAR PAQUETES

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from category_encoders import TargetEncoder
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import QuantileTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import MaxAbsScaler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

#Automcompletar rápido
%config IPCompleter.greedy=True

## IMPORTAR LOS DATOS

1.- Sustituir la ruta del proyecto.

In [6]:
ruta_proyecto = 'C:/Users/Lenovo/Documents/portafolio_ds/automation/LEAD_KAGGLE'

2.- Nombrar los archivos de datos.

In [7]:
nombre_cat = 'cat_resultado_eda.pickle'
nombre_num = 'num_resultado_eda.pickle'

3.- Cargar los datos.

In [8]:
cat = pd.read_pickle(ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_cat).reset_index(drop=True)
num = pd.read_pickle(ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_num).reset_index(drop=False)

4.- Separar la target.

In [9]:
target = num[['converted']].copy().reset_index(drop=True)

## TRANSFORMACIÓN DE CATEGÓRICAS

### One Hot Encoding

#### Variables a aplicar OHE

In [10]:
var_ohe = ['lead_origin','lead_source','last_activity','country','specialization','what_is_your_current_occupation','tags','city','last_notable_activity']

#### Instanciar

In [11]:
ohe = OneHotEncoder(sparse_output = False, handle_unknown='ignore')

#### Entrenar y aplicar

In [12]:
cat_ohe = ohe.fit_transform(cat[var_ohe])

#### Guardar como dataframe

In [13]:
cat_ohe = pd.DataFrame(cat_ohe, columns = ohe.get_feature_names_out())

### Ordinal Encoding

#### Variables a aplicar OE

In [14]:
var_oe = ['asymmetrique_activity_index','asymmetrique_profile_index']

#### Orden de los valores de las variables

In [15]:
#Orden de la primera variable
orden_activity = ['03.Low','02.Medium','01.High']

#Orden de la segunda variable
orden_profile = ['Unknown','03.Low','02.Medium','01.High']

#### Instanciar

In [16]:
oe = OrdinalEncoder(categories = [orden_activity,orden_profile],
                    handle_unknown = 'use_encoded_value',
                    unknown_value = 10)

#### Entrenar y aplicar

In [17]:
cat_oe = oe.fit_transform(cat[var_oe])

#### Guardar como dataframe

In [18]:
#Añadir sufijos a los nombres
nombres_oe = [variable + '_oe' for variable in var_oe]

#Guardar como dataframe
cat_oe = pd.DataFrame(cat_oe, columns = nombres_oe)

## UNIFICAR DATASETS TRANSFORMADOS

### Meter en una lista todos los dataframes generados

In [19]:
dataframes = []
dataframes.extend(value for name, value in locals().items() if name.startswith('cat_') or name.startswith('num'))

### Unir todos los dataframes

In [20]:
df = pd.concat(dataframes, axis = 1)

## REESCALAR VARIABLES

### Con Min-Max

#### Variables a reescalar con Min-Max

In [21]:
df.iloc[:,1:8:].columns

Index(['lead_number', 'converted', 'total_visits',
       'total_time_spent_on_website', 'page_views_per_visit',
       'asymmetrique_activity_score', 'asymmetrique_profile_score'],
      dtype='object')

In [22]:
var_mms = ['lead_number','total_visits','total_time_spent_on_website','page_views_per_visit','asymmetrique_activity_score','asymmetrique_profile_score']

#### Instanciar

In [23]:
mms = MinMaxScaler()

#### Entrenar y aplicar

In [24]:
df_mms = mms.fit_transform(df[var_mms])

#### Guardar como dataframe

In [25]:
#Añadir sufijos a los nombres
nombres_mms = [variable + '_mms' for variable in var_mms]

#Guardar como dataframe
df_mms = pd.DataFrame(df_mms,columns = nombres_mms)

## UNIFICAR DATASETS REESCALADOS

### Crear una lista con los dataframes a incluir en el tablón analítico

In [26]:
Prospect_ID = df['Prospect ID'].to_frame()
Prospect_ID

                               Prospect ID
0     7927b2df-8bba-4d29-b9a2-b6e0beafe620
1     2a272436-5132-4136-86fa-dcc88c88f482
2     8cc8c611-a219-4f35-ad23-fdfd2656bd8a
3     0cc2df48-7cf4-4e39-9de9-19797f9b38cc
4     3256f628-e534-4826-9d63-4a8b88782852
...                                    ...
5935  3f715465-2546-47cd-afa8-8b8dc63b8b43
5936  c0b25922-511f-4c56-852e-ced210a45447
5937  82a7005b-7196-4d56-95ce-a79f937a158d
5938  5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9
5939  571b5c8e-a5b2-4d57-8574-f2ffb06fdeff

[5940 rows x 1 columns]

In [70]:
incluir = [Prospect_ID, cat_ohe, cat_oe, df_mms, target]

### Unir todos los dataframes en el tablón analítico

In [71]:
df_tablon = pd.concat(incluir, axis = 1).set_index('Prospect ID')

In [72]:
df_tablon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5940 entries, 7927b2df-8bba-4d29-b9a2-b6e0beafe620 to 571b5c8e-a5b2-4d57-8574-f2ffb06fdeff
Data columns (total 66 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   lead_origin_API                                       5940 non-null   float64
 1   lead_origin_Landing Page Submission                   5940 non-null   float64
 2   lead_origin_Lead Add Form                             5940 non-null   float64
 3   lead_origin_OTHER                                     5940 non-null   float64
 4   lead_source_Direct Traffic                            5940 non-null   float64
 5   lead_source_Google                                    5940 non-null   float64
 6   lead_source_OTHER                                     5940 non-null   float64
 7   lead_source_Olark Chat                                5940 non-null   float64
 8   lead_source_Organic Search                            5940 non-null   float64
 9   lead_source_Reference                                 5940 non-null   float64
 10  last_activity_Converted to Lead                       5940 non-null   float64
 11  last_activity_Email Link Clicked                      5940 non-null   float64
 12  last_activity_Email Opened                            5940 non-null   float64
 13  last_activity_OTHER                                   5940 non-null   float64
 14  last_activity_Olark Chat Conversation                 5940 non-null   float64
 15  last_activity_Page Visited on Website                 5940 non-null   float64
 16  last_activity_SMS Sent                                5940 non-null   float64
 17  country_India                                         5940 non-null   float64
 18  country_OTHER                                         5940 non-null   float64
 19  specialization_Banking, Investment And Insurance      5940 non-null   float64
 20  specialization_Business Administration                5940 non-null   float64
 21  specialization_Finance Management                     5940 non-null   float64
 22  specialization_Human Resource Management              5940 non-null   float64
 23  specialization_IT Projects Management                 5940 non-null   float64
 24  specialization_Marketing Management                   5940 non-null   float64
 25  specialization_Media and Advertising                  5940 non-null   float64
 26  specialization_OTHER                                  5940 non-null   float64
 27  specialization_Operations Management                  5940 non-null   float64
 28  specialization_Select                                 5940 non-null   float64
 29  specialization_Supply Chain Management                5940 non-null   float64
 30  specialization_Travel and Tourism                     5940 non-null   float64
 31  what_is_your_current_occupation_OTHER                 5940 non-null   float64
 32  what_is_your_current_occupation_Student               5940 non-null   float64
 33  what_is_your_current_occupation_Unemployed            5940 non-null   float64
 34  what_is_your_current_occupation_Working Professional  5940 non-null   float64
 35  tags_Already a student                                5940 non-null   float64
 36  tags_Busy                                             5940 non-null   float64
 37  tags_Closed by Horizzon                               5940 non-null   float64
 38  tags_Interested in other courses                      5940 non-null   float64
 39  tags_OTHER                                            5940 non-null   float64
 40  tags_Ringing                                          5940 non-null   float64
 41  tags_Unknown                                          5940 non-null   float64
 42  tags_Will revert after reading the email              5940 non-null   float64
 43  tags_switched off                                     5940 non-null   float64
 44  city_Mumbai                                           5940 non-null   float64
 45  city_OTHER                                            5940 non-null   float64
 46  city_Other Cities                                     5940 non-null   float64
 47  city_Other Cities of Maharashtra                      5940 non-null   float64
 48  city_Other Metro Cities                               5940 non-null   float64
 49  city_Select                                           5940 non-null   float64
 50  city_Thane & Outskirts                                5940 non-null   float64
 51  last_notable_activity_Email Link Clicked              5940 non-null   float64
 52  last_notable_activity_Email Opened                    5940 non-null   float64
 53  last_notable_activity_Modified                        5940 non-null   float64
 54  last_notable_activity_OTHER                           5940 non-null   float64
 55  last_notable_activity_Page Visited on Website         5940 non-null   float64
 56  last_notable_activity_SMS Sent                        5940 non-null   float64
 57  asymmetrique_activity_index_oe                        5940 non-null   float64
 58  asymmetrique_profile_index_oe                         5940 non-null   float64
 59  lead_number_mms                                       5940 non-null   float64
 60  total_visits_mms                                      5940 non-null   float64
 61  total_time_spent_on_website_mms                       5940 non-null   float64
 62  page_views_per_visit_mms                              5940 non-null   float64
 63  asymmetrique_activity_score_mms                       5940 non-null   float64
 64  asymmetrique_profile_score_mms                        5940 non-null   float64
 65  converted                                             5940 non-null   int64
dtypes: float64(65), int64(1)
memory usage: 3.0+ MB

In [73]:
pd.set_option('display.max_rows', None)

In [74]:
#Revisión general de los datos
df_tablon.describe().T

,count,mean,std,min,25%,50%,75%,max
lead_origin_API,5940.0,0.404040,0.490747,0.0,0.000000,0.000000,1.000000,1.0
lead_origin_Landing Page Submission,5940.0,0.511785,0.499903,0.0,0.000000,1.000000,1.000000,1.0
lead_origin_Lead Add Form,5940.0,0.077441,0.267313,0.0,0.000000,0.000000,0.000000,1.0
lead_origin_OTHER,5940.0,0.006734,0.081791,0.0,0.000000,0.000000,0.000000,1.0
lead_source_Direct Traffic,5940.0,0.259933,0.438634,0.0,0.000000,0.000000,1.000000,1.0
lead_source_Google,5940.0,0.322054,0.467303,0.0,0.000000,0.000000,1.000000,1.0
lead_source_OTHER,5940.0,0.038889,0.193346,0.0,0.000000,0.000000,0.000000,1.0
lead_source_Olark Chat,5940.0,0.199663,0.399781,0.0,0.000000,0.000000,0.000000,1.0
lead_source_Organic Search,5940.0,0.120539,0.325618,0.0,0.000000,0.000000,0.000000,1.0
lead_source_Reference,5940.0,0.058923,0.235500,0.0,0.000000,0.000000,0.000000,1.0
last_activity_Converted to Lead,5940.0,0.052525,0.223103,0.0,0.000000,0.000000,0.000000,1.0
last_activity_Email Link Clicked,5940.0,0.033165,0.179082,0.0,0.000000,0.000000,0.000000,1.0
last_activity_Email Opened,5940.0,0.415825,0.492905,0.0,0.000000,0.000000,1.000000,1.0
last_activity_OTHER,5940.0,0.028451,0.166272,0.0,0.000000,0.000000,0.000000,1.0
last_activity_Olark Chat Conversation,5940.0,0.113636,0.317396,0.0,0.000000,0.000000,0.000000,1.0
last_activity_Page Visited on Website,5940.0,0.063131,0.243219,0.0,0.000000,0.000000,0.000000,1.0
last_activity_SMS Sent,5940.0,0.293266,0.455298,0.0,0.000000,0.000000,1.000000,1.0
country_India,5940.0,0.972559,0.163379,0.0,1.000000,1.000000,1.000000,1.0
country_OTHER,5940.0,0.027441,0.163379,0.0,0.000000,0.000000,0.000000,1.0
"specialization_Banking, Investment And Insurance",5940.0,0.038384,0.192137,0.0,0.000000,0.000000,0.000000,1.0
specialization_Business Administration,5940.0,0.044444,0.206098,0.0,0.000000,0.000000,0.000000,1.0
specialization_Finance Management,5940.0,0.103535,0.304682,0.0,0.000000,0.000000,0.000000,1.0
specialization_Human Resource Management,5940.0,0.091919,0.288936,0.0,0.000000,0.000000,0.000000,1.0
specialization_IT Projects Management,5940.0,0.035522,0.185110,0.0,0.000000,0.000000,0.000000,1.0
specialization_Marketing Management,5940.0,0.092593,0.289885,0.0,0.000000,0.000000,0.000000,1.0
specialization_Media and Advertising,5940.0,0.021549,0.145217,0.0,0.000000,0.000000,0.000000,1.0
specialization_OTHER,5940.0,0.085690,0.279930,0.0,0.000000,0.000000,0.000000,1.0
specialization_Operations Management,5940.0,0.055051,0.228098,0.0,0.000000,0.000000,0.000000,1.0
specialization_Select,5940.0,0.374074,0.483924,0.0,0.000000,0.000000,1.000000,1.0
specialization_Supply Chain Management,5940.0,0.036700,0.188041,0.0,0.000000,0.000000,0.000000,1.0
specialization_Travel and Tourism,5940.0,0.020539,0.141846,0.0,0.000000,0.000000,0.000000,1.0
what_is_your_current_occupation_OTHER,5940.0,0.003535,0.059359,0.0,0.000000,0.000000,0.000000,1.0
what_is_your_current_occupation_Student,5940.0,0.023569,0.151715,0.0,0.000000,0.000000,0.000000,1.0
what_is_your_current_occupation_Unemployed,5940.0,0.895118,0.306427,0.0,1.000000,1.000000,1.000000,1.0
what_is_your_current_occupation_Working Professional,5940.0,0.077778,0.267844,0.0,0.000000,0.000000,0.000000,1.0
tags_Already a student,5940.0,0.047980,0.213741,0.0,0.000000,0.000000,0.000000,1.0
tags_Busy,5940.0,0.020875,0.142979,0.0,0.000000,0.000000,0.000000,1.0
tags_Closed by Horizzon,5940.0,0.042256,0.201189,0.0,0.000000,0.000000,0.000000,1.0
tags_Interested in other courses,5940.0,0.056734,0.231353,0.0,0.000000,0.000000,0.000000,1.0
tags_OTHER,5940.0,0.085354,0.279431,0.0,0.000000,0.000000,0.000000,1.0
tags_Ringing,5940.0,0.129125,0.335366,0.0,0.000000,0.000000,0.000000,1.0
tags_Unknown,5940.0,0.356397,0.478975,0.0,0.000000,0.000000,1.000000,1.0
tags_Will revert after reading the email,5940.0,0.237205,0.425405,0.0,0.000000,0.000000,0.000000,1.0
tags_switched off,5940.0,0.024074,0.153292,0.0,0.000000,0.000000,0.000000,1.0
city_Mumbai,5940.0,0.340067,0.473771,0.0,0.000000,0.000000,1.000000,1.0
city_OTHER,5940.0,0.006734,0.081791,0.0,0.000000,0.000000,0.000000,1.0
city_Other Cities,5940.0,0.075253,0.263821,0.0,0.000000,0.000000,0.000000,1.0
city_Other Cities of Maharashtra,5940.0,0.050168,0.218311,0.0,0.000000,0.000000,0.000000,1.0
city_Other Metro Cities,5940.0,0.041582,0.199650,0.0,0.000000,0.000000,0.000000,1.0
city_Select,5940.0,0.406566,0.491234,0.0,0.000000,0.000000,1.000000,1.0
city_Thane & Outskirts,5940.0,0.079630,0.270742,0.0,0.000000,0.000000,0.000000,1.0
last_notable_activity_Email Link Clicked,5940.0,0.022222,0.147418,0.0,0.000000,0.000000,0.000000,1.0
last_notable_activity_Email Opened,5940.0,0.329630,0.470118,0.0,0.000000,0.000000,1.000000,1.0
last_notable_activity_Modified,5940.0,0.357239,0.479226,0.0,0.000000,0.000000,1.000000,1.0
last_notable_activity_OTHER,5940.0,0.026936,0.161910,0.0,0.000000,0.000000,0.000000,1.0
last_notable_activity_Page Visited on Website,5940.0,0.031481,0.174630,0.0,0.000000,0.000000,0.000000,1.0
last_notable_activity_SMS Sent,5940.0,0.232492,0.422456,0.0,0.000000,0.000000,0.000000,1.0
asymmetrique_activity_index_oe,5940.0,1.053199,0.357535,0.0,1.000000,1.000000,1.000000,2.0
asymmetrique_profile_index_oe,5940.0,1.337205,1.263924,0.0,0.000000,2.000000,2.000000,3.0
lead_number_mms,5940.0,0.475247,0.288993,0.0,0.218342,0.465451,0.726642,1.0
total_visits_mms,5940.0,0.066131,0.067028,0.0,0.020000,0.060000,0.100000,1.0
total_time_spent_on_website_mms,5940.0,0.214851,0.241921,0.0,0.002091,0.108715,0.418134,1.0
page_views_per_visit_mms,5940.0,0.115925,0.101845,0.0,0.050000,0.100000,0.150000,1.0
asymmetrique_activity_score_mms,5940.0,0.652219,0.094543,0.0,0.636364,0.636364,0.636364,1.0
asymmetrique_profile_score_mms,5940.0,0.576076,0.150392,0.0,0.555556,0.555556,0.555556,1.0
converted,5940.0,0.400505,0.490042,0.0,0.000000,0.000000,1.000000,1.0

In [75]:
pd.reset_option('display.max_rows')

## GUARDAR DATASET TRAS TRANSFORMACIÓN DE DATOS

En formato pickle para no perder las modificaciones de metadatos.

In [76]:
#Definir los nombres del archivo
ruta_df_tablon = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'df_tablon.pickle'

In [77]:
#Guardar los archivos
df_tablon.to_pickle(ruta_df_tablon)